# Generated by Django 4.2.8 on 2023-12-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['updated_on']},
        ),
    ]
